apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: passworm
  labels:
    app: mongo
    type: hostpath
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: microk8s-hostpath
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    type: DirectoryOrCreate
    path: "/var/data/mongo"
