apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: passworm-ingress
  namespace: passworm
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt
spec:
  tls:
  - hosts:
    - passworm.essa-vm-04.lrk.si
    secretName: passworm-ingress-tls
  rules:
  - host: passworm.essa-vm-04.lrk.si
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: passworm
            port:
              number: 3000