apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: passworm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  strategy: {}
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:6.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-auth
                  key: mongo_init_user
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-auth
                  key: mongo_init_password
            - name: MONGO_APP_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-auth
                  key: mongo_app_user
            - name: MONGO_APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-auth
                  key: mongo_app_password
            - name: MONGO_DB
              valueFrom:
                secretKeyRef:
                  name: mongo-auth
                  key: mongo_db
          volumeMounts:
            - mountPath: /data/db
              name: mongo-data
            - mountPath: /docker-entrypoint-initdb.d/
              name: init-config
              readOnly: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-pvc
        - name: init-config
          configMap:
            name: mongo-init-config
