apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init-config
  namespace: passworm
data:
  mongo_init.js: |+
    db = db.getSiblingDB(process.env[MONGO_DB]);

    db.createUser(
        {
            user: process.env[MONGO_APP_USER],
            pwd: process.env[MONGO_APP_PASSWORD],
            roles: [{ role: 'readWrite', db: process.env[MONGO_DB]}],
        },
    );