apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init-config
  namespace: passworm
data:
  mongo_init.js: |+
    const db = db.getSiblingDB('Passworm');

    db.createUser(
        {
            user: 'worm',
            pwd: 'hidden',
            roles: [{ role: 'readWrite', db: 'Passworm'}]
        }
    );