apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: passworm
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:6.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongo-data
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-pvc
