apiVersion: v1
kind: Service
metadata:
  name: passworm
  namespace: passworm
  labels:
    app: passworm
spec:
  selector:
    app: passworm
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
