---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mail-auth
  namespace: passworm
spec:
  encryptedData:
    password: AgBza3Dn7VAbOyeJYlbYq4KMTg2cuze19IrTKjoFczwgqhkS1WXU7aOhBBbUBwOvUCRs4IPUMTU9zhmGNolF9QS3+sqpe662fkJsBFNhdVCiPGpyM3GnvsIzCdqgGkuxZ3YNFfLzwJ2Fv2+HJoUrteoeH+3yxPLc2olU8+xI/StM6aFvPo58cWD2TPgskCZwmxTRVRrhTklQp6FF3Z6TJ9h159RSudHOdZYRKxcrhM40tii+cwSn28GJDxZefF5mZPZhEpVRB254Hb5b7VW2TjJlQvYkqve+bVSPxt9eJTGBG0dd7euhwGM10mzxqNRaoUnp5KcxexkUfjOBRwbVQfca3in0IfHw7bbK8y2hEgwGSMioOBJNspjjHIGEqSrMBPxYdJUnJob8tlwcxR7FQDfp4yxMqsmeLraHmYswELGjzbBH8ZDkOA6/Gyrf/SULQqW9bevfa5c5NMfG3q51MPvfqEtgk5EV9B+srjlo/YTeqODx5jrR+Kpms9K/rciZif9ttiLkpVK7bQ1wmiKjGQi3gjGsmQr1PZHEolq8KLcYcNacjD+G6PBJwnUybTOBtOKS775MCo56G+3AmpwE5HwAm2vYcjQzcst0+xaWXEjfIA+XBgxBPFP3lPD3YSPHDVF3XmKPQ5m+Uci2kQdpSySH6jjjnhA9UfPT3J0eT5oFbjliabSgWO1eg6lymnLRcS2S3mo6FGlPKPF2MFRL5BB0am1c
    username: AgCgnjMyjzzpWpea2PpHRZFfqAP4MCgGGNokxDuApKa82JYfnWU/G3+Sy6TUbV0xpY/VatCP/FOu8BF5EAqJQIvtQh1HlRnC/JWBQlwTNGFuiKhszWPln9GbAgmBr6xQrJQgH8TOoeuGd40SVTaSMD8R1KCSxMuPpeYUI1aP+mqOQMDBuXQJCBDlnl+5I0qyL8Rj9VKGOMSxKlKmJN8j5VqZX7KLAofz48o3CmWZMGDrJZuFv/WafjK9aDVoR4lz/XeGgtr0Q30dCj9YXjYvSWbEJ/7etKxwF+nbTxonRz1eeIFkAZa4x3oVs9eY61TtohwYCPsl9LyLD2z5t+OBwGQShYKOGZSm2fDWzwt9VGHgRb8g5dskmFzdt+/4aadZuTbi3mnYzHzpsnOSzhndAgc4lwrWbobBEQIZIOLERZ3hXoWOCcKPZjVMHcuhQTX5gLGiA3/j0YSqrXh6XrNTWzP50ed5mVMj77J4LH6Xf5t5pBBsc41A4Lz25EdSx/Je0CY9yFaNUYH20AudmcXJ/14znmltDiau3HB6Os4pSPvWfPoclEvVBHQo3P5h9DCB0lRgQYankW+NIkzT66NVS4SgVuP/M9iUyy2zGhPot4Xw7MGqAiDDAVxbiED3Plyv46ScIq2eLnV/DG2b3piPtbsww5/kNSkB2eNWxn6b/92EdfOX0+Hh1nCiCz5eqJ3sWr6Xkns1yjfV7hDhiWHQli1ggH4QYbyz8sLz1g==
  template:
    metadata:
      creationTimestamp: null
      name: mail-auth
      namespace: passworm
    type: kubernetes.io/basic-auth
